global_frame: map
robot_base_frame: base_link
width: 20.0
height: 20.0

plugins:
- name: static_layer
  type: costmap_2d::StaticLayer
#- name: obstacle_layer
#  type: costmap_2d::ObstacleLayer
- name: inflation_layer
  type: costmap_2d::InflationLayer

inflation_layer:
  inflation_radius: 0.4

static_layer:
  lethal_cost_threshold: 50

