recovery_behavior_enabled: true
recovery_behaviors:
- name: conservative_reset
  type: clear_costmap_recovery/ClearCostmapRecovery
- name: aggressive_reset
  type: clear_costmap_recovery/ClearCostmapRecovery

planner_frequency: 5.0
planner_patience: 5.0
controller_frequency: 10.0
controller_patience: 5.0

