base_local_planner: teb_local_planner/TebLocalPlannerROS
TebLocalPlannerROS:
  max_vel_x: 0.6
  max_vel_x_backwards: 0.3
  acc_lim_x: 3.0

  max_vel_y: 0.0
  acc_lim_y: 0.0

  max_vel_theta: 18.0
  acc_lim_theta: 18.0

  min_turning_radius: 0.6
  wheelbase: 0.3

  footprint_model:
    type: polygon
    vertices:
    - [-0.25, -0.19]
    - [ 0.25, -0.19]
    - [ 0.25,  0.19]
    - [-0.25,  0.19]

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 3.142
  free_goal_vel: true

  max_global_plan_lookahead_dist: 0.0
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 50
  weight_optimaltime: 0.5
  allow_init_with_backwards_motion: false
  teb_autosize: true

  min_obstacle_dist: 0.08
  costmap_obstacles_behind_robot_dist: 3.0
  inflation_dist: 0.1

  enable_homotopy_class_planning: false

  map_frame: odom

