publish_frequency: 5.0
update_frequency: 5.0
resolution: 0.05

footprint:
- [-0.23,-0.16]
- [-0.23,0.16]
- [0.23,0.16]
- [0.23,-0.16]

static_layer:
  track_unknown_space: true
  trinary_costmap: true
  static_map: true

obstacle_layer:
  observation_sources: scan
  scan:
    topic: scan
    data_type: LaserScan
    clearing: true
    marking: true
  track_unknown_space: false
  obstacle_range: 9.0
  raytrace_range: 10.0

