scan_filter_chain:
- name: car
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser_frame
    min_x: -0.1
    max_x: 0.4
    min_y: -0.1
    max_y: 0.1
    min_z: -0.15
    max_z: 0.1

